version: '3.8'
services:
  user_service:
    build: ./microservices/user_service
    ports:
      - "4001:4001"
    depends_on:
      - db

  task_service:
    build: ./microservices/task_service
    ports:
      - "4002:4002"
    depends_on:
      - db

  api_gateway:
    build: ./api_gateway
    ports:
      - "4000:4000"
    depends_on:
      - user_service
      - task_service

  db:
    image: postgres
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password

  redis:
    image: redis
    
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  grafana_data:
  elasticsearch_data: