global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'elixir_app'
    static_configs:
      - targets: ['user_service:4001', 'task_service:4002']
